name: Publish types to DefinitelyTyped
on:
  release:
    types:
      - published

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Checkout-js
        uses: actions/checkout@v2
        with:
          path: checkout-js
      - name: Checkout DefinitelyTyped
        uses: actions/checkout@v2
        with:
          repository: DefinitelyTyped/DefinitelyTyped
          ref: master
          path: DefinitelyTyped
          fetch-depth: 1
      - name: Create changes
        id: create-changes
        run: |
          rm checkout-js/test/types/tsconfig.json \
             checkout-js/test/types/tslint.json \
             checkout-js/test/types/index.d.ts \
             checkout-js/types/tsconfig.json \
             checkout-js/types/tslint.json

          cp -R checkout-js/types/* DefinitelyTyped/types/mybusinessapp__checkout-js
          cp -R checkout-js/test/types/* DefinitelyTyped/types/mybusinessapp__checkout-js/test

          out_version=$(cat checkout-js/package.json | jq '.version' -r )
          echo ::set-output name=version::$out_version
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: DefinitelyTyped
          commit-message: Updates checkout-js types
          branch: update-checkout-js-${{ steps.create-changes.outputs.version }}
          push-to-fork: checkout/DefinitelyTyped
          token: ${{ secrets.DEFINITELY_TYPED_PR_GITHUB_ACCESS_TOKEN }}
          title: Updates types for Checkout.js v${{ steps.create-changes.outputs.version }}
          body: |
            # Updates types for Checkout.js v${{ steps.create-changes.outputs.version }}

            View the full checkout-js release [here](https://github.com/mybusiness-app/checkout-js/releases/tag/v${{ steps.create-changes.outputs.version }})

            Note: This is an automated pull request. For more info, see the [Checkout.js](https://github.com/mybusiness-app/checkout-js) repository or [documentation](https://developers.mybusinessapp.co.za/reference/checkout-js/index.html).
